### ISSUE TITLE
telegram skill not showing 

### ISSUE THREAD

**Issue by adelorenzo** [luke5sky/telegram-skill#9]
Hello,

the telegram skill is not showing on my profile page. I tried adding the variables in settings.json but it did not work. What could I be doing wrong?

Thank you.

**Comment by TheLastProject** [comment]
I'm having the same issue. Quite new to Mycroft so wouldn't be surprised if I did something wrong, but I don't know what I'm supposed to do.

**Comment by jaykamee** [comment]
Same issue here, I have installed the skill via voice command "install telegram skill" and then confirming. The skill is installed according to assistant, when I ask "is telegram installed" the answer is "yes", also when I try to install it again in MSM it tells me it is already installed. 

But then it does not show up in the list of skill in my mycroft.ai account, so I cannot configure it.

Also, right after having installed I got the following voice message: "no or incorrect device name specified".

**Comment by orsa86** [comment]
@adelorenzo @TheLastProject @jaykamee  
I found the workaround. You need to edit ___init.py___ file in the telegram skill folder and set the chatid, auth token and device name. 

For example

"Enter Telegram ChatID"
user_id1 = self.settings.get('TeleID1', '111111111')

"Enter Mycroft Device Name"
MyCroftDevice1 = self.settings.get('MDevice1','Troll')

"Enter Telegram Auth Token"
self.bottoken = self.settings.get('TeleToken1', '111111111:AAAAABBBCCCCDDD')

**Comment by luke5sky** [comment]
i will look into this

**Comment by luke5sky** [comment]
I will push an update today to fix this.

Sorry for keeping you waiting so long!

**Comment by luke5sky** [comment]
This should work now for all Github Users (if you downloaded the skill directly from git).

All marketplace users need to wait for this pull to be accepted:
https://github.com/MycroftAI/mycroft-skills/pull/1298

If anyone got time to test it, i would appreciate it

**Comment by orsa86** [comment]
thanks, it works now.
Can you also update telegram-spam-skill?

**Comment by orsa86** [comment]
However, there is below error reported in the mycroft cli every few minutes. I do have only one telegram instance running.

` 25 | telegram.ext.updater | Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
 07:36:38.567 | ERROR    |    25 | telegram.ext.dispatcher | No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/ext/updater.py", line 380, in _network_loop_retry
    if not action_cb():
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/ext/updater.py", line 341, in polling_action_cb
    allowed_updates=allowed_updates)
  File "<decorator-gen-31>", line 2, in get_updates
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/bot.py", line 67, in decorator
    result = func(*args, **kwargs)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/bot.py", line 2097, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/utils/request.py", line 334, in post
    **urlopen_kwargs)
  File "/opt/mycroft/.venv/lib/python3.6/site-packages/telegram/utils/request.py", line 249, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
`

**Comment by luke5sky** [comment]
that looks like mycroft did not properly shutdown (and therefore the telegram-skill is running twice).
best would be to just reboot

**Comment by luke5sky** [comment]
> telegram-spam-skill

will do

**Comment by luke5sky** [comment]
> 
> 
> thanks, it works now.
> Can you also update telegram-spam-skill?

will do

**Comment by orsa86** [comment]
I did reboot entire mycroft but the error is still present. Btw, I run mycroft in docker container it that means something. Also, I am not sure how this skill should work. I get the initial message on the telegram that skill is loaded, but other than that nothing else. Can you give me one example of  the worklow? For example, If I write something in the telegram-bot should that be caught on the mycroft side?

**Comment by luke5sky** [comment]
Yes, you should be able to write to mycroft and he will respond via telegram.

It sounds like you got two telegram-skills running, did you install it via git and via marketplace?
if this is the case please uninstall one of them

**Comment by orsa86** [comment]
I recreated the entire mycroft docker container and installed telegram via git. The error message is still present, and I still only get default loading message and nothing else.

**Comment by luke5sky** [comment]
are you sure, that only one docker container with only one telegram skill is installed?
can you provide the log output from /var/log/mycroft/skills.log maybe there is more information

**Comment by luke5sky** [comment]
you can also try to create a new bot.

The error message is generate from the telegram servers not locally, therefore a new bot (if this is possible for you) should help.

Or regenerate your auth token for this bot (should do the same)

**Comment by luke5sky** [comment]
i am closing this issue now, if recreating the bot or changing the auth token does not help please open a new issue

**Comment by luke5sky** [comment]
The update was merged in the mycroft skill repository, should be available via the marketplace as of now.

Thanks for your patience
